LIBSEARCH-112. Added "require_dependency" so tests run consistently
Added "require_dependency 'search_error'" so that tests would not
fail with the following error:

NameError: uninitialized constant QuickSearch::SearcherError

depending on the order in which they were run.

https://issues.umd.edu/browse/LIBSEARCH-112